"""
CUDA to RIPPLE Translator

A comprehensive toolchain for translating CUDA code to RIPPLE for
Hexagon HVX and other SIMD targets.

Features:
    - Source-level translation (CUDA C -> RIPPLE C)
    - IR-level translation (CUDA LLVM IR -> RIPPLE LLVM IR)
    - CLI, Web, and VS Code interfaces
    - Hexagon HVX optimization

Usage:
    # As a library
    from cuda2ripple import translate
    ripple_code = translate(cuda_code, target="hexagon")
    
    # As CLI
    cuda2ripple source input.cu -o output.c
    cuda2ripple ir input.ll -o output.ll
    cuda2ripple interactive
    
    # As web server
    cuda2ripple-web --port 5000

Architecture:
    
    CUDA Source ──┐                           ┌──> RIPPLE C Code
                  ├──> Semantic AIR ──────────┤
    CUDA LLVM IR ─┘                           └──> RIPPLE LLVM IR
    
    The Semantic AIR (Abstract Intermediate Representation) bridges
    CUDA concepts to RIPPLE concepts, enabling both source-level and
    IR-level translation through a unified semantic model.

Target Platforms:
    - Hexagon HVX (primary)
    - x86-64 AVX/AVX-512
    - ARM SVE/SME

Author: Generated by Claude for LiaiZen CUDA-to-RIPPLE project
Version: 0.1.0
"""

__version__ = "0.1.0"
__author__ = "CUDA2RIPPLE"

# Core imports
from core.semantic_model import (
    TranslationContext,
    HexagonConfig,
    RIPPLEBlockShape,
    RIPPLEProcessingElement,
    AIRTranslationUnit,
    AIRFunction,
)

from core.translation_rules import (
    TranslationRuleEngine,
    TranslationRule,
    infer_block_shape,
)

# Frontend imports
from frontends.source.cuda_frontend import (
    CUDAToRIPPLETransformer,
    CUDALexer,
    translate_cuda_source,
    translate_cuda_file,
)

from frontends.ir.ir_frontend import (
    CUDAIRToRIPPLETranslator,
    translate_cuda_ir,
    analyze_cuda_ir,
)


# =============================================================================
# High-Level API
# =============================================================================

def translate(
    code: str,
    mode: str = "source",
    target: str = "hexagon",
    hvx_width: int = 128,
    hvx_mode: str = "v68"
) -> str:
    """
    Translate CUDA code to RIPPLE.
    
    Args:
        code: CUDA source code or LLVM IR
        mode: "source" for source-level, "ir" for IR-level translation
        target: Target platform ("hexagon", "x86", "arm")
        hvx_width: Hexagon HVX vector width (64 or 128 bytes)
        hvx_mode: Hexagon instruction set version
    
    Returns:
        Translated RIPPLE code
    
    Example:
        >>> cuda_code = '''
        ... __global__ void add(float *a, float *b, float *c, int n) {
        ...     int idx = threadIdx.x + blockIdx.x * blockDim.x;
        ...     if (idx < n) c[idx] = a[idx] + b[idx];
        ... }
        ... '''
        >>> ripple_code = translate(cuda_code)
        >>> print(ripple_code)
    """
    ctx = TranslationContext(
        target_platform=target,
        translation_mode=mode
    )
    
    if mode == "source":
        transformer = CUDAToRIPPLETransformer(ctx)
        return transformer.transform(code)
    elif mode == "ir":
        translator = CUDAIRToRIPPLETranslator(ctx)
        return translator.translate(code)
    else:
        raise ValueError(f"Unknown mode: {mode}. Use 'source' or 'ir'.")


def analyze(code: str, mode: str = "source") -> dict:
    """
    Analyze CUDA code without translation.
    
    Args:
        code: CUDA source code or LLVM IR
        mode: "source" or "ir"
    
    Returns:
        Dictionary with analysis results
    """
    if mode == "ir":
        result = analyze_cuda_ir(code)
        return {
            "kernels": len(result.kernels),
            "device_functions": len(result.device_functions),
            "max_block_dim": result.max_block_dim,
            "uses_shared_memory": result.uses_shared_memory,
            "uses_warp_shuffles": result.uses_warp_shuffles,
            "uses_atomics": result.uses_atomics,
        }
    else:
        lexer = CUDALexer(code)
        tokens = lexer.tokenize()
        return {
            "lines": len(code.split('\n')),
            "tokens": len(tokens),
            "has_kernels": '__global__' in code,
            "has_device_functions": '__device__' in code,
            "uses_shared_memory": '__shared__' in code,
            "uses_atomics": 'atomic' in code,
            "uses_shuffles": '__shfl' in code,
        }


# =============================================================================
# Exports
# =============================================================================

__all__ = [
    # Version
    "__version__",
    
    # High-level API
    "translate",
    "analyze",
    
    # Context
    "TranslationContext",
    "HexagonConfig",
    
    # Source frontend
    "CUDAToRIPPLETransformer",
    "CUDALexer",
    "translate_cuda_source",
    "translate_cuda_file",
    
    # IR frontend
    "CUDAIRToRIPPLETranslator",
    "translate_cuda_ir",
    "analyze_cuda_ir",
    
    # Rules
    "TranslationRuleEngine",
    "TranslationRule",
    "infer_block_shape",
    
    # Semantic model
    "RIPPLEBlockShape",
    "RIPPLEProcessingElement",
]
