[workspace]
members = ["crates/ripple-rustc-probe", "crates/ripple-ir", "crates/ripple-codegen"]
exclude = ["fixtures/kernel", "crates/ripple-kernel"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
publish = false

[workspace.dependencies]
serde = { version = "=1.0.219", features = ["derive"] }
serde_json = "=1.0.140"
